[pytest]
# Отключаем cacheprovider, чтобы не создавать проблемные временные каталоги на Windows.
addopts = -p no:cacheprovider

# Переназначаем директорию кэша на путь с гарантированными правами.
cache_dir = C:\\Users\\anton\\AppData\\Local\\pytest_cache
