param(
    [string]$BaseBranch = "develop",
    [string]$Title = "Feature: Streamlit UI and OCI config alignment"
)

$ErrorActionPreference = "Stop"

# 1. Определяем текущую ветку
$CurrentBranch = git rev-parse --abbrev-ref HEAD

if ($CurrentBranch -eq $BaseBranch) {
    Write-Host "Current branch is the base branch ($BaseBranch), nothing to PR." -ForegroundColor Yellow
    exit 1
}

Write-Host "Creating PR from '$CurrentBranch' into '$BaseBranch'..." -ForegroundColor Cyan

# 2. Ищем открытый PR для этой ветки
try {
    $ExistingPrJson = gh pr list `
        --base $BaseBranch `
        --head $CurrentBranch `
        --state open `
        --json number,title,body `
        --limit 1
} catch {
    Write-Host "gh pr list failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}

$ExistingPr = $null
if ($ExistingPrJson) {
    $ExistingPr = $ExistingPrJson | ConvertFrom-Json
}

# 2. Коммиты и изменённые файлы
$SummaryLines = "Introduce changes from branch `$CurrentBranch` into `$BaseBranch`."
$CommitsRange = "$BaseBranch..$CurrentBranch"
$CommitsList = git log --oneline $CommitsRange
$ChangedFiles = git diff --name-only "$BaseBranch...$CurrentBranch"
$RisksLines = @"
- Low risk: this PR only affects PR metadata tooling (scripts and docs-assistant integration).
- No application runtime behavior (finder, CLI, UI) is changed directly by this script.
"@
$ConfigLines = @"
- No production configuration changes in this iteration.
- Local tooling assumes:
  - GitHub CLI (`gh`) is installed and authenticated.
  - `scripts/pr.ps1` is run from within the repository root.
"@
$TestingLines = "Local:
  - `pytest -vv`
- CI:
  - `lint-and-test` workflows on supported Python versions."
$NotesLines = "This PR body is a standard template generated by `scripts/pr.ps1`.
For richer documentation (Summary / Changes / Risks / Config / Testing), trigger the docs-assistant workflow via `[review-pr]` to let `code_to_docs.py` update title, body, and labels."

if (-not $ChangedFiles) {
    Write-Host "No changes between $BaseBranch and $CurrentBranch, nothing to PR." -ForegroundColor Yellow
    exit 1
}

$ChangesLines = $ChangedFiles | ForEach-Object { "- $_" } | Out-String

# 3. Стандартный Markdown-body
$Body = @"
## Summary

$SummaryLines
## Changes

$ChangesLines
## Commits

$CommitsList

## Risks

$RisksLines
## Config

$ConfigLines
## Testing

$TestingLines
## Notes

$NotesLines
"@

# 5. Если PR уже есть — обновляем, иначе создаём
if ($ExistingPr -and $ExistingPr.number) {
    $PrNumber = $ExistingPr.number
    Write-Host "Open PR #$PrNumber found for branch '$CurrentBranch'. Updating it..." -ForegroundColor Green

    gh pr edit $PrNumber `
        --title $Title `
        --body $Body
} else {
    Write-Host "No open PR found for branch '$CurrentBranch'. Creating a new one..." -ForegroundColor Cyan

    gh pr create `
      --base $BaseBranch `
      --head $CurrentBranch `
      --title $Title `
      --body $Body
}
